# Generated by Django 4.2.8 on 2023-12-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoteCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Note Category",
                "verbose_name_plural": "Note Categories",
                "db_table": "note_category",
            },
        ),
        migrations.CreateModel(
            name="NoteStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Note Status",
                "verbose_name_plural": "Note Statuses",
                "db_table": "note_status",
            },
        ),
        migrations.CreateModel(
            name="NoteTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Note Tag",
                "verbose_name_plural": "Note Tags",
                "db_table": "note_tag",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Title", max_length=255, unique=True, verbose_name="Title"
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="howto.notecategory")),
                ("status", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="howto.notestatus")),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="notes", related_query_name="note", to="howto.notetag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "db_table": "note",
            },
        ),
    ]
