# Generated by Django 4.2.8 on 2023-12-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("howto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notestatus",
            name="name",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("deprecated", "Deprecated"),
                ],
                default="draft",
                max_length=20,
                unique=True,
            ),
        ),
    ]
