# Generated by Django 4.2.8 on 2023-12-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("howto", "0002_alter_notestatus_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("deprecated", "Deprecated"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="NoteStatus",
        ),
    ]
