# Generated by Django 4.2.8 on 2023-12-19 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("howto", "0003_alter_note_status_delete_notestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                related_query_name="note",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
